Started by upstream project "[8mha:////4B6NhAHPgMPJg3YzrE5MgtZyWGwldzIKjfjjGQ5DRDBkAAAAqx+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyJEgYl/az8JP3i1KKyzOTUYjCnJD8lXzexoEA3vygxOSdVHwAFTOH/1wAAAA==[0mservices/todo-app-oracle" build number [8mha:////4CmcypdLbEzkNlw/nAtj5hMXz2i+/dOd/1Rrm0BlXQSKAAAAqx+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLQIwSBmX9rPwk/eLUorLM5NRiMKckPyVfN7GgQDe/KDE5J1XfGAD5vNPs2AAAAA==[0m3
originally caused by:
 Started by user [8mha:////4HSKTYekCqJtgUzvE/X25d7VYiaybRQPqPlqTWr6Yj8mAAAAmR+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAz+EgZe/dLi1CL9xOKMzOKMPAD2nB5TwgAAAA==[0mAshish Nanotkar
Building in workspace /var/lib/jenkins/workspace/common/delphix-refresh-vdb
Set build name.
New build name is 'devdb'
[delphix-refresh-vdb] $ python /tmp/jenkins8629292170693833519.py
Traceback (most recent call last):
  File "/tmp/jenkins8629292170693833519.py", line 46, in <module>
    container_env['DEPLOY_ENV'] = os.environ['DEPLOY_ENV']
  File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'DEPLOY_ENV'
Build step 'Execute Python script' marked build as failure
Set build name.
New build name is 'devdb'
Variable with name 'BUILD_DISPLAY_NAME' already exists, current value: 'devdb', new value: 'devdb'
Finished: FAILURE
